# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:latest

stages:
  - npm
  - test

npm:
  stage: npm
  script:
    - npm install
  cache:
    paths:
      - node_modules/


test:
  stage: test
  dependencies:
    - npm
  script:
    - npm run test-jenkins
